// Generated by CoffeeScript 1.6.3
(function() {
  var addMapLine, dropMapMarker, initializeGoogleMaps, snowAPI;

  snowAPI = 'http://dev.stadilumi.fi/api/v1/snowplow/';

  initializeGoogleMaps = function(callback) {
    var map, mapOptions, styles;
    mapOptions = {
      center: new google.maps.LatLng(60.193084, 24.940338),
      zoom: 13,
      disableDefaultUI: true
    };
    styles = [
      {
        "elementType": "labels",
        "stylers": [
          {
            "visibility": "off"
          }
        ]
      }, {
        "stylers": [
          {
            "invert_lightness": true
          }, {
            "hue": "#00bbff"
          }, {
            "weight": 0.4
          }, {
            "saturation": 100
          }
        ]
      }
    ];
    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
    map.setOptions({
      styles: styles
    });
    return callback(map);
  };

  dropMapMarker = function(map, plowJobColor, lat, lng) {
    var marker, snowPlowMarker;
    snowPlowMarker = {
      path: "M10 10 H 90 V 90 H 10 L 10 10",
      fillColor: plowJobColor,
      strokeColor: plowJobColor,
      strokeWeight: 7,
      strokeOpacity: 0.8,
      scale: 0.01
    };
    return marker = new google.maps.Marker({
      position: new google.maps.LatLng(lat, lng),
      map: map,
      icon: snowPlowMarker
    });
  };

  addMapLine = function(map, plowData, plowTrailColor) {
    var polyline, polylinePath;
    polylinePath = _.reduce(plowData.history, (function(accu, x) {
      accu.push(new google.maps.LatLng(x.coords[1], x.coords[0]));
      return accu;
    }), []);
    polyline = new google.maps.Polyline({
      path: polylinePath,
      geodesic: true,
      strokeColor: plowTrailColor,
      strokeWeight: 2,
      strokeOpacity: 0.6
    });
    return polyline.setMap(map);
  };

  $(document).ready(function() {
    var createPlowTrail, createPlowsOnMap, getActivePlows;
    getActivePlows = function(map, callback) {
      var plowPositions;
      plowPositions = Bacon.fromPromise($.getJSON(snowAPI + '?since=12hours+ago&callback=?'));
      plowPositions.onValue(function(json) {
        return callback(map, json);
      });
      return plowPositions.onError(function(error) {
        return console.error("Failed to fetch active snowplows: " + (JSON.stringify(error)));
      });
    };
    createPlowTrail = function(map, plowId, plowTrailColor) {
      var plowPositions;
      plowPositions = Bacon.fromPromise($.getJSON(snowAPI + plowId + '?history=1000&callback=?'));
      plowPositions.onValue(function(json) {
        return addMapLine(map, json, plowTrailColor);
      });
      return plowPositions.onError(function(error) {
        return console.error("Failed to create snowplow trail for plow " + plowId + ": " + error);
      });
    };
    createPlowsOnMap = function(map, json) {
      var getPlowJobColor;
      getPlowJobColor = function(job) {
        switch (job) {
          case "kv":
            return "#b6e78f";
          case "au":
            return "#b83800";
          case "su":
            return "#ff0113";
          case "hi":
            return "#8530a0";
          default:
            return "#ffffff";
        }
      };
      return _.each(json, function(x) {
        var plowJobColor;
        plowJobColor = getPlowJobColor(x.last_loc.events[0]);
        createPlowTrail(map, x.id, plowJobColor);
        return dropMapMarker(map, plowJobColor, x.last_loc.coords[1], x.last_loc.coords[0]);
      });
    };
    return initializeGoogleMaps(function(map) {
      return getActivePlows(map, function(map, json) {
        return createPlowsOnMap(map, json);
      });
    });
  });

  console.log("%c                                                                               \n      _________                            .__                                 \n     /   _____/ ____   ______  _  ________ |  |   ______  _  ________          \n     \\_____  \\ /    \\ /  _ \\ \\/ \\/ /\\____ \\|  |  /  _ \\ \\/ \\/ /  ___/          \n     /        \\   |  (  <_> )     / |  |_> >  |_(  <_> )     /\\___ \\           \n    /_______  /___|  /\\____/ \\/\\_/  |   __/|____/\\____/ \\/\\_//____  >          \n            \\/     \\/ .__           |__|     .__  .__             \\/   .___    \n                ___  _|__| ________ _______  |  | |__|_______ ____   __| _/    \n        Sampsa  \\  \\/ /  |/  ___/  |  \\__  \\ |  | |  \\___   // __ \\ / __ |     \n        Kuronen  \\   /|  |\\___ \\|  |  // __ \\|  |_|  |/    /\\  ___// /_/ |     \n            2014  \\_/ |__/____  >____/(____  /____/__/_____ \\\\___  >____ |     \n                              \\/           \\/              \\/    \\/     \\/     \n                  https://github.com/sampsakuronen/snowplow-visualization      \n                                                                               ", 'background: #001e29; color: #00bbff');

}).call(this);
